# Site settings
title: MachinevLearning in Production
email: 
description: "Machine learning engineers"
baseurl: ""
url: "MachineLearninginProduction.github.io"
github_username:  MachineLearninginProduction

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
